# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 770c2d112d47d04b0a5f20173e3a8d0d3682fc6d69068f6f9b585298f60e6e852b48c8142cd3f582955d360942d7b30318b01839f40f827d296bb41d70167868

test:
  secret_key_base: 62518b008aea5ca7e92e39cc94bb6a191eb1bc511dabf5cf46d4884346c37d3faa959af4ffe8d9b14adf6f88fc4beb804fee2936b1f210f73068d13915190e7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
